/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as mainRouteRouteImport } from './routes/(main)/route'
import { Route as mainIndexRouteImport } from './routes/(main)/index'
import { Route as mainAnimatedPunkIconIndexRouteImport } from './routes/(main)/animated-punk-icon/index'

const mainRouteRoute = mainRouteRouteImport.update({
  id: '/(main)',
  getParentRoute: () => rootRouteImport,
} as any)
const mainIndexRoute = mainIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => mainRouteRoute,
} as any)
const mainAnimatedPunkIconIndexRoute =
  mainAnimatedPunkIconIndexRouteImport.update({
    id: '/animated-punk-icon/',
    path: '/animated-punk-icon/',
    getParentRoute: () => mainRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof mainIndexRoute
  '/animated-punk-icon/': typeof mainAnimatedPunkIconIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof mainIndexRoute
  '/animated-punk-icon': typeof mainAnimatedPunkIconIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(main)': typeof mainRouteRouteWithChildren
  '/(main)/': typeof mainIndexRoute
  '/(main)/animated-punk-icon/': typeof mainAnimatedPunkIconIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/animated-punk-icon/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/animated-punk-icon'
  id: '__root__' | '/(main)' | '/(main)/' | '/(main)/animated-punk-icon/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  mainRouteRoute: typeof mainRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(main)': {
      id: '/(main)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof mainRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(main)/': {
      id: '/(main)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof mainIndexRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(main)/animated-punk-icon/': {
      id: '/(main)/animated-punk-icon/'
      path: '/animated-punk-icon'
      fullPath: '/animated-punk-icon/'
      preLoaderRoute: typeof mainAnimatedPunkIconIndexRouteImport
      parentRoute: typeof mainRouteRoute
    }
  }
}

interface mainRouteRouteChildren {
  mainIndexRoute: typeof mainIndexRoute
  mainAnimatedPunkIconIndexRoute: typeof mainAnimatedPunkIconIndexRoute
}

const mainRouteRouteChildren: mainRouteRouteChildren = {
  mainIndexRoute: mainIndexRoute,
  mainAnimatedPunkIconIndexRoute: mainAnimatedPunkIconIndexRoute,
}

const mainRouteRouteWithChildren = mainRouteRoute._addFileChildren(
  mainRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  mainRouteRoute: mainRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
